### ISSUE TITLE
Appium.WebDriver@5.0.0 compatibility with WinAppDriver 

### ISSUE THREAD

**Issue by dtopuzov** [appium/dotnet-client#487] opened 2021-11-28 15:17 UTC
## Description

Appium.WebDriver@5.0.0-beta01 can not work with https://github.com/microsoft/WinAppDriver directly.
The reason is `WinAppDriver` want `app` capability to be set, while `Appium.WebDriver` prefix and makes it `appium:app`.

Referace:
https://github.com/appium/appium-dotnet-driver/blob/release/5.0.0/src/Appium.Net/Appium/AppiumOptions.cs#L15

To keep compatiblity with WinAppDriver I would like to have a way to create cabalities object that allows me to have `app` with the prefix.

I understand that ideally the fix should be on WinAppDriver side, but currently it still [using deprecated JSON wire protocol](https://github.com/microsoft/WinAppDriver/issues/1610) :(

## Environment

* .NET client build version or git revision if you use some shapshot: Appium.WebDriver@5.0.0-beta01
* Appium server version or git revision if you use some shapshot: appium@2.0.0-beta.23
* Desktop OS/version used to run Appium if necessary: Windows 10/11
* Node.js version (unless using Appium.app|exe) or Appium CLI or Appium.app|exe: 14
* Mobile platform/version under test: Windows Desktop

## Details

The use case is:
- I try to build cross platform automation for Android/iOS/MacOS/Windows via Appium
- For Windows I tries to use https://github.com/microsoft/WinAppDriver directly because I had issues when using via `appium`.

**Comment by mykola-mokhnach** [comment] 2021-11-28 16:51
I don't see any point in adding the support of the legacy JWP protocol into the driver just because Microsoft has abandoned the support for their WAD server. Also, it still works being used together with Appium as the latter is capable of requests  transformation between W3C<>JWP.

**Comment by mykola-mokhnach** [comment] 2021-11-28 16:53
You could also consider creating a fork of the project

**Comment by mg-diego** [comment] 2022-01-17 15:47
Hi! Any news on this topic? I'm facing the same problem on my project and so far we could not find any solution in order to be able to use our WinAppDriver testcases in case we migrate to Selenium v4 + Appium driver.

Thanks in advance

**Comment by TroyWalshProf** [comment] 2022-02-01 14:17
@dtopuzov 
The beta kind of work with WinAppDriver, as long as you are interacting with it thru the Appium client.
Here is roughly how to get and run the Appium client
> npm install -g appium  # get appium
> npm install wd         # get appium client
> appium &               # start appium

*Note** Basically all "Action" calls will fail, see:
https://github.com/microsoft/WinAppDriver/issues/1610
https://github.com/appium/appium/issues/16268

**Comment by grokys** [comment] 2022-10-26 08:25
Is my current understanding of the state of Appium/WinAppDriver correct?

- [We should be using Appium 2.0](https://github.com/appium/appium/discussions/15828#discussioncomment-3863882), Appium 1.0 is no longer supported
- To use Appium 2.0 from .NET, we need to use the Appium.WebDriver 5.0.0-beta 
- 5.0.0-beta no longer supports communicating with WinAppDriver directly, need to go via Appium
- WinAppDriver when going via Appium doesn't support [Actions with mouse or keyboard events](https://github.com/appium/appium/issues/16268)

So essentially, we're forced into a choice:

- Stay with unsupported Appium 1.0, or
- Lose support for testing mouse and keyboard events

Is this accurate?

**Comment by Dor-bl** [comment] 2022-10-30 03:52
@grokys 5.0.0 beta worked for me with winapp driver. Can you please give an example what is not working for you?

**Comment by grokys** [comment] 2022-11-02 11:56
@Dor-bl I'm seeing the problem described by this issue:

> The reason is WinAppDriver want app capability to be set, while Appium.WebDriver prefix and makes it appium:app.

Specifically, I see:

```
Windows Application Driver listening for requests at: http://127.0.0.1:4723/
Press ENTER to exit.


==========================================
POST /session HTTP/1.1
Accept: application/json; charset=utf-8
Content-Length: 249
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/4.0.0 (.net windows)
X-Idempotency-Key: def0c1a2-c88f-4d06-9c73-ceff3c423fbe

{"capabilities":{"firstMatch":[{"platformName":"Windows","appium:app":"D:\\projects\\AvaloniaUI\\Avalonia\\samples\\IntegrationTestApp\\bin\\Debug\\net6.0\\IntegrationTestApp.exe","appium:automationName":"Windows","appium:deviceName":"WindowsPC"}]}}
HTTP/1.1 400 Bad Request
Content-Length: 141
Content-Type: application/json

{"status":100,"value":{"error":"invalid argument","message":"Bad capabilities. Specify either app or appTopLevelWindow to create a session"}}
```

**Comment by yizhao5** [comment] 2022-11-03 04:37
@Dor-bl. Hello. How did you work successfully in version [v5.0.0-beta02](https://github.com/appium/appium-dotnet-driver/releases/tag/v5.0.0-beta02)?

**Description**
The basic function of constructing `WindowsDriver` with appium-dotnet-driver's version v5.0.0-beta02 goes error.
![image](https://user-images.githubusercontent.com/109595412/199640402-5063ae79-273a-4a04-8fa2-2da870104f67.png)
Error log:
`{"status":100,"value":{"error":"invalid argument","message":"Bad capabilities. Specify either app or appTopLevelWindow to create a session"}}`

**Version**
OS: Windows 11.
dotnet: .NET Framework 4.7.2
WinAppDriver: [WinAppDriver v1.2.1](https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.1).
appium: use [VS Nuget cmd](https://www.nuget.org/packages/Appium.WebDriver/5.0.0-beta02): `dotnet add package Appium.WebDriver --version 5.0.0-beta02`

**Repro Steps**
1. create a VS 2022 console project.
![image](https://user-images.githubusercontent.com/109595412/199638734-05025540-ec20-41b4-8791-48fa2ad222b2.png)
2. sample code:
`Program.cs`
```cs
using OpenQA.Selenium.Appium.Windows;
using System;

namespace ConsoleApp1
{
	internal class Program
	{
		static void Main(string[] args)
		{
			const string appId = @"C:\Program Files\WindowsApps\Microsoft.WindowsNotepad_11.2208.25.0_x64__8wekyb3d8bbwe\Notepad\Notepad.exe";

			var appiumOptions = new OpenQA.Selenium.Appium.AppiumOptions();
			appiumOptions.App = appId;
			var _ = new WindowsDriver(new Uri("http://127.0.0.1:4723"), appiumOptions);
		}
	}
}
```
3. first click `C:\Program Files (x86)\Windows Application Driver\WinAppDriver.exe`, then click the VS 2022's Start button to launch, and an error occurred.
![image](https://user-images.githubusercontent.com/109595412/199639666-914274c2-75ac-4bcd-8001-18f56973080f.png)

@Dor-bl, @akinsolb, @licanhua, @timotiusmargo. Can you fix it? Or just upgrade the current `Appium.WebDriver 4.4.0`'s internal dependency package `Selenium.WebDriver 3.141.0` to `Selenium.WebDriver 4.5.1`, so that users can use the latter's new features, such as `EdgeOptions.UseWebView = true;`. Thanks.

**Similar issue:**
[WinAppDriver using deprecated JSON wire protocol #1610](https://github.com/microsoft/WinAppDriver/issues/1610)
[Error raised when launching the app: Specify either app or appTopLevelWindow to create a session #1774](https://github.com/microsoft/WinAppDriver/issues/1774)
[Unable to Initiate Session with WinAppDriver #1592](https://github.com/appium/java-client/issues/1592)
[OpenQA.Selenium.WebDriverArgumentException: Bad capabilities. Specify either app or appTopLevelWindow to create a session #492](https://github.com/appium/appium-dotnet-driver/issues/492)

**Comment by licanhua** [comment] 2022-11-03 05:51
@yizhao5 I guess you didn't use appium or something is wrong in the middle. WinAppDriver is expecting `app:` other than `appium:app`, so you may remove `appium` prefix and try again?

![image](https://user-images.githubusercontent.com/6290692/199655303-cc82d45e-5fe1-4f6a-b061-feb2b0191a1f.png)

**Comment by yizhao5** [comment] 2022-11-03 06:38
@licanhua, thanks for your reply. Yes, `appium-dotnet-driver` [v5.0.0-beta02](https://github.com/appium/appium-dotnet-driver/releases/tag/v5.0.0-beta02) has been refactored. The prefix `appium:` is automatically added in the `appium-dotnet-driver v5.0.0-beta02`.
![image](https://user-images.githubusercontent.com/109595412/199657664-287208de-ac69-45e8-9c7c-a430e3d8b1e8.png)
I listed the **Repro Steps** above, and similar issues all have the same error log `Bad capabilities. Specify either app or appTopLevelWindow to create a session`.

@Dor-bl. The customers' requirement is hoping to use new features of Selenium 4. The function of `Appium.WebDriver 4.4.0` is good enough. Can you upgrade its internal dependency package `Selenium.WebDriver` from `3.141.0` to `4.5.1`? Thanks.

**Comment by Dor-bl** [comment] 2022-11-03 09:45
Indeed, I can see this error as well.
I Didn't have it while using Appium1.0, but Apparently something related to Appium 2.0.
@akinsolb I'm looking into it, but if you can have a look as well that would be great. 
in the meantime, we can add the bug label to this issue.

**Comment by Dor-bl** [comment] 2023-01-01 10:10
@yizhao5 looking over at your comment it's not possible to update the dependency package of `Selenium.WebDriver` from `3.141.0` to `4.5.1` since it will break the stable release.
if users want to use the latest version of `Selenium.WebDriver`  they will need to use the Beta release of the `Appium.WebDriver `

**Comment by kfertitta** [comment] 2023-01-12 14:55
@Dor-bl We're running WinAppDriver (1.2.1) alone as we're only testing desktop apps.  I'm still seeing this issue with `5.0.0-beta03`.  Been pouring over the various issues and discussions and it's not clear (to me, anyway) which Appium.WebServer version should go with which WinAppDriver version.  I'm also trying to get info from the WinAppDriver side of the fence.

Our UI tests and page object models are growing rapidly, so we want try to get on a sustainable path.  There were a lot of code changes going from the old `Microsoft.WinAppDriver.Appium.WebDriver` preview, so it's a big switch we have to flip.  Any thoughts and guidance are much appreciated.

**Comment by Dor-bl** [comment] 2023-03-06 18:08
@kfertitta Sorry for the late response, basically as long as Microsoft doesn't decide to allocate resources to the WinAppDriver projects our hands are tied here since the Appium-DotNet client fully supports W3C protocol while the WinAppDriver doesn't.  
regardless of the latest version of the DotNet client removed any support for page object models.
My suggestion to you is to raise issues on the WinAppDriver and hope for someone at Microsoft to notice :(

**Comment by kfertitta** [comment] 2023-03-06 18:33
@Dor-bl Thanks much for the reply.  Indeed, we are trying to get attention on the Microsoft side.  It is the only way this can move forward it seems.  As our UI testing code base grows, we continually question if it's wise to continue to build upon a foundation that has such a questionable future.  And yet, there doesn't really seem to be a better alternative out there for desktop testing.  Though we're willing to pay for a commercial solution, I'm not convinced those would actually be as good.  Hard to know where to go from here.

**Comment by Dor-bl** [comment] 2023-03-06 18:56
@kfertitta I took a quick look again at my configuration when running the Windows Integration tests, maybe this will assist you.

Appium Server v2.0.0-beta.xx 
[ Appium Windows Driver windows@2.1.2 ](https://github.com/appium/appium-windows-driver)
[WinAppDriver v1.2.1](https://github.com/microsoft/WinAppDriver/releases/tag/v1.2.1)

with the above configuration, I was able to run a basic test even when I pass appium:app 
![image](https://user-images.githubusercontent.com/59066376/223204466-59c6fe06-c81b-42ba-9f47-d374d0438e76.png)

**Comment by Schepetkov** [comment] 2023-04-07 05:48
Installation:
npm i -g appium@next
appium driver install --source=npm appium-windows-driver

Same problem:
![image](https://user-images.githubusercontent.com/29506847/230548768-44b9a61d-07dd-457e-b495-21d5b00e3bf6.png)
![image](https://user-images.githubusercontent.com/29506847/230548828-9203f81d-4a05-405e-96bb-90a7fcaec863.png)
![image](https://user-images.githubusercontent.com/29506847/230548854-9334c0fe-86b6-4524-82d4-088b70f3ff39.png)

Any idea when they will start doing something to fix this problem?
Automation for the desktop is of very low quality, with constant dancing with the tambourine.

**Comment by Dor-bl** [comment] 2023-04-07 05:55
@Schepetkov in order to use "appium:app" you will need to start the Appium server that will act as a proxy, rather than starting the WinAppDriver

**Comment by Dor-bl** [comment] 2024-05-04 18:20
I am closing this issue since Microsoft has no intentions of maintaining its WinAppDriver in the near future.
I found that https://github.com/FlaUI/FlaUI.WebDriver might be a good option for those looking to Automate Windows Applications with W3C compatibility.

**Closed by Dor-bl** 2024-05-04 18:20 UTC
Labels: ThirdParty, W3C, windowsDriver

**Comment by PeterExtrapreneur** [comment] 2024-07-17 13:20
> I am closing this issue since Microsoft has no intentions of maintaining its WinAppDriver in the near future. I found that https://github.com/FlaUI/FlaUI.WebDriver might be a good option for those looking to Automate Windows Applications with W3C compatibility.

So the only way forward for projects that has UWP and WPF that use Selenium/Appium is to refactor to FlaUI? Appium v5 left WAD and seleniums action class is also deprecated.

**Comment by Dor-bl** [comment] 2024-07-17 13:34
@PeterExtrapreneur, I didn't drop WAD from v5; I don't see a reason to maintain that driver if Microsoft doesn't, either.
Indeed, I suggest you migrate to FlaUI. If you have issues or adjustments, you can always open a ticket on their side. They are pretty responsive and open-minded about making it work with the Appium dotnet client.

**Comment by avi8045** [comment] 2025-01-30 13:17
Hi Team ,
 
Do we have any solution for this app capability support issue with Appium webdriver 7 . I updated my Appium webdriver from 4.3.1 to 7.3 and want to migrate , but winappdriver is not supporting the app capabilities.

Im getting below error . Any comments ???

Windows Application Driver listening for requests at: http://127.0.0.1:4723/
Press ENTER to exit.


==========================================
POST /session HTTP/1.1
Accept: application/json; charset=utf-8
Connection: Keep-Alive
Content-Length: 277
Content-Type: application/json; charset=utf-8
Host: 127.0.0.1:4723
User-Agent: selenium/4.27.0 (.net windows)
X-Idempotency-Key: ee30ad68-3f9b-4b1e-bfad-53e065d0008b


HTTP/1.1 400 Bad Request
Content-Length: 141
Content-Type: application/json

{"status":100,"value":{"error":"invalid argument","message":"Bad capabilities. Specify either app or appTopLevelWindow to create a session"}}

**Comment by a-einstein** [comment] 2025-08-14 19:39
I was in the process op updating packages within my WPF-application.
When updating Appium.WebDriver from 4.4.5 to 8.0.0 I was confronted with this pesty 'Bad capabilities' exception.

I may have been confronted with it before, without realising.
Now I spent time on everything that could be a possible cause.
In code, and also in the environment with regards to Appium Windows Driver and WinAppDriver.

Finally I had to conclude this issue wasthe cause, and revert a couple of things.
An absolute waste of time, because of something that seems a simple issue about prefixes.

I don't understand how this issues has persisted al the way from version 5.0.0 to 8.0.0 currently.
